version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
volumes:
  db_data:
